apiVersion: v1
kind: PersistentVolume
metadata:
  name: record-pv-volume
  labels:
    type: local
spec:
  storageClassName: record-storage-v1
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"